services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
    ports:
      - 5432:5432
 
volumes:
  pgdata: